#include "strings.h"

struct StrPair
{
	const char *en, *ar;
};

static const StrPair kStrings[S_Count] = {
	/* S_AppTitle */ {"Typing Adventure", "مغامرة الكتابة"},
	/* S_PlugKeyboard */ {"Please plug in a keyboard", "من فضلك صل لوحة المفاتيح"},
	/* S_WhoIsTyping */ {"Who is typing today?", "من سيكتب اليوم؟"},
	/* S_NewPlayer */ {"New player", "لاعب جديد"},
	/* S_TypeYourName */ {"Type your name", "اكتب اسمك"},
	/* S_NameHint */ {"Tab: English / Arabic    Enter: done    Esc: back",
			  "Tab: عربي / English    Enter: تم    Esc: رجوع"},
	/* S_PickColor */ {"Left / Right: pick your color", "يمين / يسار: اختر لونك"},
	/* S_DeleteQuestion */ {"Remove this player?", "هل تريد حذف هذا اللاعب؟"},
	/* S_DeleteHint */ {"Y: remove    Esc: keep", "Y: حذف    Esc: إلغاء"},
	/* S_ChooseCourse */ {"Choose a course", "اختر الدورة"},
	/* S_Lesson */ {"Lesson", "الدرس"},
	/* S_NewKeys */ {"New keys", "حروف جديدة"},
	/* S_Review */ {"Review", "مراجعة"},
	/* S_ReviewAll */ {"Review all the keys you know", "راجع كل الحروف التي تعرفها"},
	/* S_Capitals */ {"Capital letters", "الحروف الكبيرة"},
	/* S_Final */ {"Final challenge", "التحدي الأخير"},
	/* S_PressStart */ {"Press Enter to start", "اضغط Enter للبدء"},
	/* S_BalloonGame */ {"Balloon Pop", "فرقعة البالونات"},
	/* S_Badges */ {"Badges", "الأوسمة"},
	/* S_Accuracy */ {"Accuracy", "الدقة"},
	/* S_Speed */ {"Speed", "السرعة"},
	/* S_Wpm */ {"WPM", "كلمة/د"},
	/* S_Points */ {"Points", "النقاط"},
	/* S_Combo */ {"Combo", "سلسلة"},
	/* S_BestCombo */ {"Best combo", "أطول سلسلة"},
	/* S_Stars3 */ {"Amazing! Perfect typing!", "رائع! كتابة ممتازة!"},
	/* S_Stars2 */ {"Great job! Now try a little faster.", "أحسنت! حاول الآن أن تكون أسرع قليلا."},
	/* S_Stars1 */ {"Good work! Fewer mistakes earn more stars.",
			"عمل جيد! أخطاء أقل تعني نجوما أكثر."},
	/* S_Stars0 */ {"Almost! Slow down and aim for accuracy.", "اقتربت! تمهل وركز على الدقة."},
	/* S_ResultsHint */ {"Enter: next    R: try again    Esc: map",
			     "Enter: التالي    R: إعادة    Esc: الخريطة"},
	/* S_ResultsHintFail */ {"Enter: try again    Esc: map", "Enter: حاول مرة أخرى    Esc: الخريطة"},
	/* S_LessonComplete */ {"Lesson complete!", "أكملت الدرس!"},
	/* S_TryAgainTitle */ {"Keep practising!", "واصل التدريب!"},
	/* S_Paused */ {"Paused", "توقف مؤقت"},
	/* S_PauseHint */ {"Enter: continue    Esc: leave lesson", "Enter: متابعة    Esc: الخروج من الدرس"},
	/* S_UseOtherShift */ {"Tip: press Shift with your other hand", "تلميح: اضغط Shift باليد الأخرى"},
	/* S_CapsLockOn */ {"Caps Lock is on - press it to turn it off",
			    "مفتاح Caps Lock يعمل - اضغطه لإيقافه"},
	/* S_GameOver */ {"Game over", "انتهت اللعبة"},
	/* S_Score */ {"Score", "النتيجة"},
	/* S_Best */ {"Best", "الأفضل"},
	/* S_Level */ {"Level", "المستوى"},
	/* S_NewRecord */ {"New record!", "رقم قياسي جديد!"},
	/* S_GameIntroLetters */ {"Type the letters to pop the balloons before they fly away!",
				 "اكتب الحروف لتفرقع البالونات قبل أن تطير!"},
	/* S_GameIntroWords */ {"Type the words to pop the balloons before they fly away!",
			       "اكتب الكلمات لتفرقع البالونات قبل أن تطير!"},
	/* S_GameModeHint */ {"Tab: letters / words    Up / Down: level    Enter: play    Esc: back",
			     "Tab: حروف / كلمات    أعلى / أسفل: المستوى    Enter: العب    Esc: رجوع"},
	/* S_GameLocked */ {"Finish lesson 1 to unlock", "أكمل الدرس الأول لفتحها"},
	/* S_StartLevel */ {"Start at level", "ابدأ من المستوى"},
	/* S_BestWithLetters */ {"Best level with these letters", "أفضل مستوى بهذه الحروف"},
	/* S_LevelsBeaten */ {"Levels", "المستويات"},
	/* S_Letters */ {"Letters", "حروف"},
	/* S_Words */ {"Words", "كلمات"},
	/* S_MapHint */ {"Arrows: choose    Enter: start    Esc: back    F2: sound",
			"الأسهم: اختيار    Enter: ابدأ    Esc: رجوع    F2: الصوت"},
	/* S_ProfilesHint */ {"Arrows: choose    Enter: play    Delete: remove player",
			     "الأسهم: اختيار    Enter: العب    Delete: حذف لاعب"},
	/* S_CourseHint */ {"Arrows: choose    Enter: open    Esc: players",
			   "الأسهم: اختيار    Enter: افتح    Esc: اللاعبون"},
	/* S_TrickyKeys */ {"Keys to practise", "حروف تحتاج تدريبا"},
	/* S_NoMistakes */ {"No mistakes at all!", "بلا أي خطأ!"},
	/* S_NewBadge */ {"New badge!", "وسام جديد!"},
	/* S_Use */ {"Use your", "استخدم"},
	/* S_HomeRowTip */ {"Rest your fingers on the home row. Feel the bumps on F and J.",
			   "ضع أصابعك على الصف الأوسط. تحسس النتوءين على ب و ت."},
	/* S_ReviewIntro */ {"Practise all the keys you have learned so far.",
			    "تدرب على كل الحروف التي تعلمتها حتى الآن."},
	/* S_CapitalsIntro */ {"Hold Shift with one hand and press the letter with the other hand.",
			      "اضغط Shift بيد، والحرف باليد الأخرى."},
	/* S_FinalIntro */ {"Type real sentences using everything you have learned!",
			   "اكتب جملا حقيقية بكل ما تعلمته!"},
	/* S_Best2 */ {"Your best", "أفضل نتيجة"},
	/* S_Locked */ {"Finish the lesson before this one to unlock it.",
		       "أكمل الدرس السابق لفتح هذا الدرس."},
	/* S_SoundOn */ {"Sound on", "الصوت يعمل"},
	/* S_SoundOff */ {"Sound off", "الصوت متوقف"},
	/* S_BadgesHint */ {"Arrows: look    Esc: back", "الأسهم: تصفح    Esc: رجوع"},
	/* S_GameHint */ {"Esc: stop", "Esc: توقف"},
	/* S_EscPause */ {"Esc: pause", "Esc: إيقاف مؤقت"},
	/* S_SpaceKey */ {"space", "مسافة"},
	/* S_NoStorage */ {"Progress cannot be saved: check the SD card", "لا يمكن حفظ التقدم: افحص بطاقة الذاكرة"},
	/* S_Tip0 */ {"Keep your eyes on the screen, not on your hands.", "انظر إلى الشاشة، لا إلى يديك."},
	/* S_Tip1 */ {"Accuracy first. Speed will come with practice.",
		     "الدقة أولا، والسرعة تأتي مع التدريب."},
	/* S_Tip2 */ {"Sit up straight with your feet flat on the floor.",
		     "اجلس مستقيما وقدماك على الأرض."},
	/* S_Tip3 */ {"Press the space bar with your thumb.", "اضغط مفتاح المسافة بإبهامك."},
	/* S_Tip4 */ {"After each key, return your finger to the home row.",
		     "بعد كل حرف، أعد إصبعك إلى الصف الأوسط."},
	/* S_Tip5 */ {"Type with a gentle, steady rhythm.", "اكتب بإيقاع هادئ وثابت."},
	/* S_Tip6 */ {"Take a short break if your hands feel tired.", "خذ استراحة قصيرة إذا تعبت يداك."},
	/* S_FingerLPinky */ {"left little finger", "الخنصر الأيسر"},
	/* S_FingerLRing */ {"left ring finger", "البنصر الأيسر"},
	/* S_FingerLMiddle */ {"left middle finger", "الوسطى اليسرى"},
	/* S_FingerLIndex */ {"left pointer finger", "السبابة اليسرى"},
	/* S_FingerThumb */ {"thumb", "الإبهام"},
	/* S_FingerRIndex */ {"right pointer finger", "السبابة اليمنى"},
	/* S_FingerRMiddle */ {"right middle finger", "الوسطى اليمنى"},
	/* S_FingerRRing */ {"right ring finger", "البنصر الأيمن"},
	/* S_FingerRPinky */ {"right little finger", "الخنصر الأيمن"},
	/* S_Rank0 */ {"Seedling", "برعم"},
	/* S_Rank1 */ {"Explorer", "مستكشف"},
	/* S_Rank2 */ {"Adventurer", "مغامر"},
	/* S_Rank3 */ {"Keyboard Knight", "فارس لوحة المفاتيح"},
	/* S_Rank4 */ {"Speed Star", "نجم السرعة"},
	/* S_Rank5 */ {"Typing Hero", "بطل الكتابة"},
	/* S_Rank6 */ {"Typing Champion", "بطل الأبطال"},
	/* S_Rank7 */ {"Grand Master", "الأستاذ الكبير"},
};

const char *Str(StrId id, Lang lang) { return lang == LangAr ? kStrings[id].ar : kStrings[id].en; }

const u16 kRankStars[kRankCount] = {0, 6, 15, 30, 50, 75, 105, 140};

const BadgeText kBadges[B_Count] = {
	{"1", 0x4CAF50, {"First Steps", "الخطوة الأولى"}, {"Finish your first lesson", "أكمل أول درس"}},
	{"asdf", 0x2196F3, {"Home Row Hero", "بطل الصف الأوسط"},
	 {"Finish all the home row lessons", "أكمل كل دروس الصف الأوسط"}},
	{"100%", 0xE91E63, {"Perfect!", "ممتاز!"}, {"Finish a lesson with no mistakes", "أكمل درسا بلا أي خطأ"}},
	{"50", 0xFF9800, {"Combo 50", "سلسلة ٥٠"}, {"Type 50 keys in a row without a mistake", "اكتب ٥٠ حرفا متتاليا دون خطأ"}},
	{"100", 0xF44336, {"Combo 100", "سلسلة ١٠٠"},
	 {"Type 100 keys in a row without a mistake", "اكتب مئة حرف دون أي خطأ"}},
	{"20", 0x00BCD4, {"Speedy", "سريع"}, {"Reach 20 words per minute", "صل إلى ٢٠ كلمة في الدقيقة"}},
	{"30", 0x3F51B5, {"Rocket", "صاروخ"}, {"Reach 30 words per minute", "صل إلى ٣٠ كلمة في الدقيقة"}},
	{"30", 0xFFC107, {"Star Collector", "جامع النجوم"}, {"Collect 30 stars", "اجمع ٣٠ نجمة"}},
	{"A-Z", 0x9C27B0, {"All the Letters", "كل الحروف"},
	 {"Learn every letter in a course", "تعلم كل حروف دورة كاملة"}},
	{"100", 0xFF5722, {"Balloon Popper", "مفرقع البالونات"},
	 {"Score 100 in Balloon Pop", "اجمع ١٠٠ نقطة في فرقعة البالونات"}},
	{"300", 0x795548, {"Balloon Master", "سيد البالونات"},
	 {"Score 300 in Balloon Pop", "اجمع ٣٠٠ نقطة في فرقعة البالونات"}},
	{"A ب", 0x009688, {"Bilingual", "ثنائي اللغة"},
	 {"Earn stars in English and Arabic", "اجمع نجوما في العربية والإنجليزية"}},
	{"A+", 0x607D8B, {"Graduate", "الخريج"}, {"Finish the final challenge", "أكمل التحدي الأخير"}},
};
