#include "strings.h"

struct StrPair
{
	const char *s[LangCount];  // English, Arabic, Urdu
};

static const StrPair kStrings[S_Count] = {
	/* S_AppTitle */ {"Typing Adventure", "مغامرة الكتابة",
		"ٹائپنگ کی مہم"},
	/* S_PlugKeyboard */ {"Please plug in a keyboard", "من فضلك صل لوحة المفاتيح",
		"براہِ کرم کی بورڈ لگائیں"},
	/* S_WhoIsTyping */ {"Who is typing today?", "من سيكتب اليوم؟",
		"آج کون ٹائپ کرے گا؟"},
	/* S_NewPlayer */ {"New player", "لاعب جديد",
		"نیا کھلاڑی"},
	/* S_TypeYourName */ {"Type your name", "اكتب اسمك",
		"اپنا نام لکھیں"},
	/* S_NameHint */ {"Tab: English / Arabic / Urdu    Enter: done    Esc: back",
			  "Tab: English / عربي / اردو    Enter: تم    Esc: رجوع",
		"Tab: English / عربی / اردو    Enter: ٹھیک ہے    Esc: واپس"},
	/* S_PickColor */ {"Left / Right: pick your color", "يمين / يسار: اختر لونك",
		"دائیں / بائیں: اپنا رنگ چنیں"},
	/* S_DeleteQuestion */ {"Remove this player?", "هل تريد حذف هذا اللاعب؟",
		"کیا یہ کھلاڑی ہٹا دیں؟"},
	/* S_DeleteHint */ {"Y: remove    Esc: keep", "Y: حذف    Esc: إلغاء",
		"Y: ہٹائیں    Esc: رہنے دیں"},
	/* S_ChooseCourse */ {"Choose a course", "اختر الدورة",
		"کورس چنیں"},
	/* S_Lesson */ {"Lesson", "الدرس",
		"سبق"},
	/* S_NewKeys */ {"New keys", "حروف جديدة",
		"نئے حروف"},
	/* S_Review */ {"Review", "مراجعة",
		"دہرائی"},
	/* S_ReviewAll */ {"Review all the keys you know", "راجع كل الحروف التي تعرفها",
		"جو حروف آپ جانتے ہیں سب دہرائیں"},
	/* S_Capitals */ {"Capital letters", "الحروف الكبيرة",
		"بڑے حروف"},
	/* S_Final */ {"Final challenge", "التحدي الأخير",
		"آخری چیلنج"},
	/* S_PressStart */ {"Press Enter to start", "اضغط Enter للبدء",
		"شروع کرنے کے لیے Enter دبائیں"},
	/* S_BalloonGame */ {"Balloon Pop", "فرقعة البالونات",
		"غبارے پھوڑو"},
	/* S_Badges */ {"Badges", "الأوسمة",
		"تمغے"},
	/* S_Accuracy */ {"Accuracy", "الدقة",
		"درستی"},
	/* S_Speed */ {"Speed", "السرعة",
		"رفتار"},
	/* S_Wpm */ {"WPM", "كلمة/د",
		"لفظ/منٹ"},
	/* S_Points */ {"Points", "النقاط",
		"پوائنٹس"},
	/* S_Combo */ {"Combo", "سلسلة",
		"سلسلہ"},
	/* S_BestCombo */ {"Best combo", "أطول سلسلة",
		"سب سے لمبا سلسلہ"},
	/* S_Stars3 */ {"Amazing! Perfect typing!", "رائع! كتابة ممتازة!",
		"زبردست! بہترین ٹائپنگ!"},
	/* S_Stars2 */ {"Great job! Now try a little faster.", "أحسنت! حاول الآن أن تكون أسرع قليلا.",
		"شاباش! اب تھوڑا تیز لکھنے کی کوشش کریں۔"},
	/* S_Stars1 */ {"Good work! Fewer mistakes earn more stars.",
			"عمل جيد! أخطاء أقل تعني نجوما أكثر.",
		"اچھا کام! کم غلطیاں، زیادہ ستارے۔"},
	/* S_Stars0 */ {"Almost! Slow down and aim for accuracy.", "اقتربت! تمهل وركز على الدقة.",
		"بس تھوڑا سا اور! آہستہ لکھیں اور درستی پر دھیان دیں۔"},
	/* S_ResultsHint */ {"Enter: next    R: try again    Esc: map",
			     "Enter: التالي    R: إعادة    Esc: الخريطة",
		"Enter: اگلا    R: دوبارہ    Esc: نقشہ"},
	/* S_ResultsHintFail */ {"Enter: try again    Esc: map", "Enter: حاول مرة أخرى    Esc: الخريطة",
		"Enter: پھر کوشش کریں    Esc: نقشہ"},
	/* S_LessonComplete */ {"Lesson complete!", "أكملت الدرس!",
		"سبق مکمل!"},
	/* S_TryAgainTitle */ {"Keep practising!", "واصل التدريب!",
		"مشق جاری رکھیں!"},
	/* S_Paused */ {"Paused", "توقف مؤقت",
		"وقفہ"},
	/* S_PauseHint */ {"Enter: continue    Esc: leave lesson", "Enter: متابعة    Esc: الخروج من الدرس",
		"Enter: جاری رکھیں    Esc: سبق چھوڑیں"},
	/* S_UseOtherShift */ {"Tip: press Shift with your other hand", "تلميح: اضغط Shift باليد الأخرى",
		"مشورہ: Shift دوسرے ہاتھ سے دبائیں"},
	/* S_CapsLockOn */ {"Caps Lock is on - press it to turn it off",
			    "مفتاح Caps Lock يعمل - اضغطه لإيقافه",
		"Caps Lock آن ہے - بند کرنے کے لیے اسے دبائیں"},
	/* S_GameOver */ {"Game over", "انتهت اللعبة",
		"کھیل ختم"},
	/* S_Score */ {"Score", "النتيجة",
		"اسکور"},
	/* S_Best */ {"Best", "الأفضل",
		"بہترین"},
	/* S_Level */ {"Level", "المستوى",
		"لیول"},
	/* S_NewRecord */ {"New record!", "رقم قياسي جديد!",
		"نیا ریکارڈ!"},
	/* S_GameIntroLetters */ {"Type the letters to pop the balloons before they fly away!",
				 "اكتب الحروف لتفرقع البالونات قبل أن تطير!",
		"غبارے اڑ جانے سے پہلے حروف لکھ کر انہیں پھوڑیں!"},
	/* S_GameIntroWords */ {"Type the words to pop the balloons before they fly away!",
			       "اكتب الكلمات لتفرقع البالونات قبل أن تطير!",
		"غبارے اڑ جانے سے پہلے الفاظ لکھ کر انہیں پھوڑیں!"},
	/* S_GameModeHint */ {"Tab: letters / words    Up / Down: level    Enter: play    Esc: back",
			     "Tab: حروف / كلمات    أعلى / أسفل: المستوى    Enter: العب    Esc: رجوع",
		"Tab: حروف / الفاظ    اوپر / نیچے: لیول    Enter: کھیلیں    Esc: واپس"},
	/* S_GameLocked */ {"Finish lesson 1 to unlock", "أكمل الدرس الأول لفتحها",
		"کھولنے کے لیے پہلا سبق مکمل کریں"},
	/* S_StartLevel */ {"Start at level", "ابدأ من المستوى",
		"شروع کا لیول"},
	/* S_BestWithLetters */ {"Best level with these letters", "أفضل مستوى بهذه الحروف",
		"ان حروف کے ساتھ بہترین لیول"},
	/* S_LevelsBeaten */ {"Levels", "المستويات",
		"لیول"},
	/* S_YourBestScore */ {"Your best score", "أفضل نتيجة لك",
		"آپ کا بہترین اسکور"},
	/* S_TopScore */ {"Top score", "أعلى نتيجة",
		"سب سے اونچا اسکور"},
	/* S_NewTopScore */ {"New top score for everyone!", "أعلى نتيجة بين الجميع!",
		"سب کھلاڑیوں میں سب سے اونچا اسکور!"},
	/* S_Letters */ {"Letters", "حروف",
		"حروف"},
	/* S_Words */ {"Words", "كلمات",
		"الفاظ"},
	/* S_MapHint */ {"Arrows: choose    Enter: start    Esc: back    F2: sound",
			"الأسهم: اختيار    Enter: ابدأ    Esc: رجوع    F2: الصوت",
		"تیر: چنیں    Enter: شروع    Esc: واپس    F2: آواز"},
	/* S_ProfilesHint */ {"Arrows: choose    Enter: play    Delete: remove player",
			     "الأسهم: اختيار    Enter: العب    Delete: حذف لاعب",
		"تیر: چنیں    Enter: کھیلیں    Delete: کھلاڑی ہٹائیں"},
	/* S_CourseHint */ {"Arrows: choose    Enter: open    Esc: players",
			   "الأسهم: اختيار    Enter: افتح    Esc: اللاعبون",
		"تیر: چنیں    Enter: کھولیں    Esc: کھلاڑی"},
	/* S_TrickyKeys */ {"Keys to practise", "حروف تحتاج تدريبا",
		"ان حروف کی مشق کریں"},
	/* S_NoMistakes */ {"No mistakes at all!", "بلا أي خطأ!",
		"کوئی غلطی نہیں!"},
	/* S_NewBadge */ {"New badge!", "وسام جديد!",
		"نیا تمغا!"},
	/* S_Use */ {"Use your", "استخدم",
		"یہ انگلی استعمال کریں:"},
	/* S_HomeRowTip */ {"Rest your fingers on the home row. Feel the bumps on F and J.",
			   "ضع أصابعك على الصف الأوسط. تحسس النتوءين على ب و ت.",
		"انگلیاں درمیانی قطار پر رکھیں۔ ف اور ج پر ابھار محسوس کریں۔"},
	/* S_ReviewIntro */ {"Practise all the keys you have learned so far.",
			    "تدرب على كل الحروف التي تعلمتها حتى الآن.",
		"اب تک سیکھے ہوئے سب حروف کی مشق کریں۔"},
	/* S_CapitalsIntro */ {"Hold Shift with one hand and press the letter with the other hand.",
			      "اضغط Shift بيد، والحرف باليد الأخرى.",
		"ایک ہاتھ سے Shift دبائیں اور دوسرے ہاتھ سے حرف۔"},
	/* S_FinalIntro */ {"Type real sentences using everything you have learned!",
			   "اكتب جملا حقيقية بكل ما تعلمته!",
		"جو کچھ سیکھا ہے اس سے اصلی جملے لکھیں!"},
	/* S_Best2 */ {"Your best", "أفضل نتيجة",
		"آپ کا بہترین"},
	/* S_Locked */ {"Finish the lesson before this one to unlock it.",
		       "أكمل الدرس السابق لفتح هذا الدرس.",
		"اسے کھولنے کے لیے پچھلا سبق مکمل کریں۔"},
	/* S_SoundOn */ {"Sound on", "الصوت يعمل",
		"آواز آن"},
	/* S_SoundOff */ {"Sound off", "الصوت متوقف",
		"آواز بند"},
	/* S_BadgesHint */ {"Arrows: look    Esc: back", "الأسهم: تصفح    Esc: رجوع",
		"تیر: دیکھیں    Esc: واپس"},
	/* S_GameHint */ {"Esc: stop", "Esc: توقف",
		"Esc: رکیں"},
	/* S_EscPause */ {"Esc: pause", "Esc: إيقاف مؤقت",
		"Esc: وقفہ"},
	/* S_SpaceKey */ {"space", "مسافة",
		"اسپیس"},
	/* S_NoStorage */ {"Progress cannot be saved: check the SD card", "لا يمكن حفظ التقدم: افحص بطاقة الذاكرة",
		"ترقی محفوظ نہیں ہو سکتی: ایس ڈی کارڈ چیک کریں"},
	/* S_Tip0 */ {"Keep your eyes on the screen, not on your hands.", "انظر إلى الشاشة، لا إلى يديك.",
		"اپنی نظر اسکرین پر رکھیں، ہاتھوں پر نہیں۔"},
	/* S_Tip1 */ {"Accuracy first. Speed will come with practice.",
		     "الدقة أولا، والسرعة تأتي مع التدريب.",
		"پہلے درستی، رفتار مشق سے آئے گی۔"},
	/* S_Tip2 */ {"Sit up straight with your feet flat on the floor.",
		     "اجلس مستقيما وقدماك على الأرض.",
		"سیدھے بیٹھیں اور پاؤں زمین پر رکھیں۔"},
	/* S_Tip3 */ {"Press the space bar with your thumb.", "اضغط مفتاح المسافة بإبهامك.",
		"اسپیس بار انگوٹھے سے دبائیں۔"},
	/* S_Tip4 */ {"After each key, return your finger to the home row.",
		     "بعد كل حرف، أعد إصبعك إلى الصف الأوسط.",
		"ہر حرف کے بعد انگلی درمیانی قطار پر واپس لائیں۔"},
	/* S_Tip5 */ {"Type with a gentle, steady rhythm.", "اكتب بإيقاع هادئ وثابت.",
		"آرام سے اور ایک سی رفتار سے ٹائپ کریں۔"},
	/* S_Tip6 */ {"Take a short break if your hands feel tired.", "خذ استراحة قصيرة إذا تعبت يداك.",
		"ہاتھ تھک جائیں تو تھوڑا آرام کر لیں۔"},
	/* S_FingerLPinky */ {"left little finger", "الخنصر الأيسر",
		"بائیں چھنگلی"},
	/* S_FingerLRing */ {"left ring finger", "البنصر الأيسر",
		"بائیں تیسری انگلی"},
	/* S_FingerLMiddle */ {"left middle finger", "الوسطى اليسرى",
		"بائیں بیچ کی انگلی"},
	/* S_FingerLIndex */ {"left pointer finger", "السبابة اليسرى",
		"بائیں شہادت کی انگلی"},
	/* S_FingerThumb */ {"thumb", "الإبهام",
		"انگوٹھا"},
	/* S_FingerRIndex */ {"right pointer finger", "السبابة اليمنى",
		"دائیں شہادت کی انگلی"},
	/* S_FingerRMiddle */ {"right middle finger", "الوسطى اليمنى",
		"دائیں بیچ کی انگلی"},
	/* S_FingerRRing */ {"right ring finger", "البنصر الأيمن",
		"دائیں تیسری انگلی"},
	/* S_FingerRPinky */ {"right little finger", "الخنصر الأيمن",
		"دائیں چھنگلی"},
	/* S_Rank0 */ {"Seedling", "برعم",
		"کونپل"},
	/* S_Rank1 */ {"Explorer", "مستكشف",
		"کھوجی"},
	/* S_Rank2 */ {"Adventurer", "مغامر",
		"مہم جو"},
	/* S_Rank3 */ {"Keyboard Knight", "فارس لوحة المفاتيح",
		"کی بورڈ کا سورما"},
	/* S_Rank4 */ {"Speed Star", "نجم السرعة",
		"تیز رفتار ستارہ"},
	/* S_Rank5 */ {"Typing Hero", "بطل الكتابة",
		"ٹائپنگ ہیرو"},
	/* S_Rank6 */ {"Typing Champion", "بطل الأبطال",
		"ٹائپنگ چیمپئن"},
	/* S_Rank7 */ {"Grand Master", "الأستاذ الكبير",
		"استادِ اعظم"},
	/* S_NewRank */ {"New rank: ", "رتبة جديدة: ",
		"نیا درجہ: "},
};

const char *Str(StrId id, Lang lang) { return kStrings[id].s[lang]; }

const u16 kRankStars[kRankCount] = {0, 6, 15, 30, 50, 75, 105, 140};

const BadgeText kBadges[B_Count] = {
	{"1", 0x4CAF50, {"First Steps", "الخطوة الأولى", "پہلا قدم"}, {"Finish your first lesson", "أكمل أول درس", "اپنا پہلا سبق مکمل کریں"}},
	{"asdf", 0x2196F3, {"Home Row Hero", "بطل الصف الأوسط", "درمیانی قطار کا ہیرو"},
	 {"Finish all the home row lessons", "أكمل كل دروس الصف الأوسط", "درمیانی قطار کے سب سبق مکمل کریں"}},
	{"100%", 0xE91E63, {"Perfect!", "ممتاز!", "بے مثال!"}, {"Finish a lesson with no mistakes", "أكمل درسا بلا أي خطأ", "بغیر کسی غلطی کے سبق مکمل کریں"}},
	{"50", 0xFF9800, {"Combo 50", "سلسلة ٥٠", "سلسلہ ۵۰"}, {"Type 50 keys in a row without a mistake", "اكتب ٥٠ حرفا متتاليا دون خطأ", "بغیر غلطی کے لگاتار ۵۰ حروف لکھیں"}},
	{"100", 0xF44336, {"Combo 100", "سلسلة ١٠٠", "سلسلہ ۱۰۰"},
	 {"Type 100 keys in a row without a mistake", "اكتب مئة حرف دون أي خطأ", "بغیر غلطی کے لگاتار ۱۰۰ حروف لکھیں"}},
	{"20", 0x00BCD4, {"Speedy", "سريع", "تیز"}, {"Reach 20 words per minute", "صل إلى ٢٠ كلمة في الدقيقة", "۲۰ الفاظ فی منٹ تک پہنچیں"}},
	{"30", 0x3F51B5, {"Rocket", "صاروخ", "راکٹ"}, {"Reach 30 words per minute", "صل إلى ٣٠ كلمة في الدقيقة", "۳۰ الفاظ فی منٹ تک پہنچیں"}},
	{"30", 0xFFC107, {"Star Collector", "جامع النجوم", "ستارے جمع کرنے والا"}, {"Collect 30 stars", "اجمع ٣٠ نجمة", "۳۰ ستارے جمع کریں"}},
	{"A-Z", 0x9C27B0, {"All the Letters", "كل الحروف", "سب حروف"},
	 {"Learn every letter in a course", "تعلم كل حروف دورة كاملة", "کسی کورس کے سب حروف سیکھیں"}},
	{"100", 0xFF5722, {"Balloon Popper", "مفرقع البالونات", "غبارے پھوڑنے والا"},
	 {"Score 100 in Balloon Pop", "اجمع ١٠٠ نقطة في فرقعة البالونات", "غبارے پھوڑو میں ۱۰۰ اسکور کریں"}},
	{"300", 0x795548, {"Balloon Master", "سيد البالونات", "غباروں کا استاد"},
	 {"Score 300 in Balloon Pop", "اجمع ٣٠٠ نقطة في فرقعة البالونات", "غبارے پھوڑو میں ۳۰۰ اسکور کریں"}},
	{"A ب", 0x009688, {"Bilingual", "ثنائي اللغة", "دو زبانیں"},
	 {"Earn stars in two courses", "اجمع نجوما في دورتين", "دو کورسز میں ستارے جمع کریں"}},
	{"A+", 0x607D8B, {"Graduate", "الخريج", "فارغ التحصیل"}, {"Finish the final challenge", "أكمل التحدي الأخير", "آخری چیلنج مکمل کریں"}},
};
