#!/usr/bin/env python3
"""Pre-render the fonts used by the typing tutor into a C++ source file.

The Pi has no font engine: every glyph is rasterised here, on the build
machine, into 8-bit alpha bitmaps that the kernel blends onto the screen.
Arabic is rendered from its presentation forms (U+FE70..U+FEFC), so the
kernel only has to pick the right isolated/initial/medial/final form.
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
LATIN_FONT = ROOT / "assets/fonts/Andika-Bold.ttf"
ARABIC_FONT = ROOT / "assets/fonts/NotoNaskhArabic.ttf"

# Must match enum FontSize in src/core/font.h
SIZES = [("Small", 22), ("Body", 30), ("Title", 44), ("Type", 58), ("Huge", 120)]
ARABIC_SCALE = 1.15          # Naskh looks smaller than Latin at the same em size

ASCII = list(range(0x20, 0x7F))
LATIN_EXTRA = [0x00D7, 0x00F7, 0x2018, 0x2019]  # × ÷ ‘ ’ (Arabic-layout shift keys)
ARABIC_BASE = list(range(0x060C, 0x060D)) + [0x061B, 0x061F] + list(range(0x0621, 0x063B)) \
    + list(range(0x0640, 0x064B)) + list(range(0x064B, 0x0653)) + list(range(0x0660, 0x066B))
ARABIC_FORMS = list(range(0xFE70, 0xFEFD))
# Huge size is only used for single letters/keys, so keep it small.
HUGE_LATIN = [c for c in ASCII if chr(c).isalnum() or chr(c) in " ;,./'?-=[]`\\%+"]
# Isolated presentation forms (what a lone letter shapes to), lam-alef, digits.
HUGE_ARABIC = [0xFE80, 0xFE81, 0xFE83, 0xFE85, 0xFE87, 0xFE89, 0xFE8D, 0xFE8F, 0xFE93, 0xFE95,
               0xFE99, 0xFE9D, 0xFEA1, 0xFEA5, 0xFEA9, 0xFEAB, 0xFEAD, 0xFEAF, 0xFEB1, 0xFEB5,
               0xFEB9, 0xFEBD, 0xFEC1, 0xFEC5, 0xFEC9, 0xFECD, 0xFED1, 0xFED5, 0xFED9, 0xFEDD,
               0xFEE1, 0xFEE5, 0xFEE9, 0xFEED, 0xFEEF, 0xFEF1, 0xFEF5, 0xFEF7, 0xFEF9, 0xFEFB,
               0x060C, 0x061F] + list(range(0x0660, 0x066B))


def render_face(path, px, codepoints, arabic):
    font = ImageFont.truetype(str(path), px, layout_engine=ImageFont.Layout.BASIC)
    ascent, descent = font.getmetrics()
    glyphs, blob = [], bytearray()
    cmap = TTFont(str(path)).getBestCmap()
    for cp in sorted(set(codepoints)):  # Find() does a binary search
        if cp not in cmap and cp != 0x20:
            continue
        ch = chr(cp)
        adv = round(font.getlength(ch))
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        off = len(blob)
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
            blob += img.tobytes()
        glyphs.append((cp, w, h, x0, y0, adv, off))
    return dict(glyphs=glyphs, blob=blob, ascent=ascent, descent=descent)


def emit(out, name, face):
    out.append(f"static const u8 {name}_bits[] = {{")
    b = face["blob"]
    for i in range(0, len(b), 32):
        out.append("  " + ",".join(str(v) for v in b[i:i + 32]) + ",")
    out.append("  0 };")
    out.append(f"static const Glyph {name}_glyphs[] = {{")
    for g in face["glyphs"]:
        out.append("  {0x%04X,%d,%d,%d,%d,%d,%d}," % g)
    out.append("};")
    return (f"{{{name}_glyphs, {len(face['glyphs'])}, {name}_bits, "
            f"{face['ascent']}, {face['descent']}}}")


def main():
    dst = Path(sys.argv[1])
    out = ["// Generated by scripts/gen_fonts.py -- do not edit.",
           "// Glyphs from Andika (SIL OFL 1.1) and Noto Naskh Arabic (SIL OFL 1.1).",
           '#include "font.h"', "", "namespace font {"]
    latin, arabic = [], []
    total = 0
    for sname, px in SIZES:
        huge = sname == "Huge"
        lf = render_face(LATIN_FONT, px, HUGE_LATIN if huge else ASCII + LATIN_EXTRA, False)
        af = render_face(ARABIC_FONT, round(px * ARABIC_SCALE),
                         HUGE_ARABIC if huge else ARABIC_BASE + ARABIC_FORMS, True)
        latin.append(emit(out, f"latin_{sname}", lf))
        arabic.append(emit(out, f"arabic_{sname}", af))
        total += len(lf["blob"]) + len(af["blob"])
    out.append("const Face g_Latin[SizeCount] = {" + ", ".join(latin) + "};")
    out.append("const Face g_Arabic[SizeCount] = {" + ", ".join(arabic) + "};")
    out.append("} // namespace font")
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(out) + "\n")
    print(f"gen_fonts: {dst} ({total // 1024} KiB of glyph bitmaps)")


if __name__ == "__main__":
    main()
